name: 游戏组推送on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  schedule:
    # - cron: 0 22,14 * * * 北京时间每天8点自动执行
    - cron: 0 4 * * * 
  watch:
    types: started

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
      - uses: actions/checkout@v2
      - name: 初始化Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: 推送ing
        run: |
          pip install -r requirements.txt
          echo 开始推送
          python3 main.py
